package io.github.bitaron.auditlog.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a method whose invocations should be recorded as audit log entries.
 * <p>
 * Applying this annotation to a method causes the audit-log starter's AOP aspect to intercept
 * both successful returns and thrown exceptions, capture the method's arguments and outcome,
 * and (by default, asynchronously and off the caller's thread - see
 * {@code AuditLogProperties.DeliveryMode}) persist one audit record per matching template in
 * {@link #templates()}.
 * <p>
 * {@code @Target} includes {@code TYPE} and this annotation is {@code @Repeatable}, matching how
 * annotations of this kind are conventionally declared. Stacking two or more {@code @Audit} on
 * one method is fully supported - see {@link Audits}; applying it at {@code TYPE} level is
 * accepted by the compiler but not yet processed by the aspect.
 */
@Documented
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
@Repeatable(Audits.class)
public @interface Audit {

    /**
     * A high-level category for the audited action (e.g. "AUTH", "PAYMENT", "USER_MANAGEMENT").
     * Stored verbatim on the persisted {@code AuditLog} record.
     *
     * @return the audit type; required, has no default
     */
    String auditType();

    /**
     * A short, human-readable name for the specific action being audited (e.g. "login-attempt").
     *
     * @return the action name, or empty string if not set
     */
    String actionName() default "";

    /**
     * The kind of operation being audited (e.g. "CREATE", "UPDATE", "DELETE").
     *
     * @return the action type, or empty string if not set
     */
    String actionType() default "";

    /**
     * When set, records generated by this invocation are associated with a shared audit group,
     * useful for correlating multiple audit entries produced by one logical operation.
     *
     * @return the group name, or empty string to skip grouping
     */
    String groupName() default "";

    /**
     * Names of the {@code audit_template} rows used to render this method's audit message(s).
     * One audit log row is persisted per matching, existing template name. If empty, a single
     * audit log row is still persisted with a default message and no template association.
     *
     * @return the template names to resolve against
     */
    String[] templates() default {};

    /**
     * How the actor for this audit record is determined. See {@link ActorSource}.
     *
     * @return the actor resolution strategy; {@link ActorSource#CONTEXT} by default
     */
    ActorSource actorSource() default ActorSource.CONTEXT;

    /**
     * SpEL expression evaluated when {@link #actorSource()} is {@link ActorSource#EXPRESSION},
     * against a root object exposing {@code #result} (the method's return value), {@code #args}
     * (its arguments, as an array), and {@code #exception} (the thrown exception, or {@code null}
     * on success). The resolved value becomes both the actor id and actor name.
     * <p>
     * Replaces the pre-2.0 design, where setting {@code isActorCommon=false} required the audited
     * method's return type to implement {@code AuditLogGenericDataGetter} so the aspect could
     * downcast it - an intrusive coupling between the audit annotation and the business method's
     * own type. Example: {@code @Audit(actorSource = EXPRESSION, actorExpression = "#result.ownerId")}.
     *
     * @return the SpEL expression to evaluate, or empty string if not using {@code EXPRESSION}
     */
    String actorExpression() default "";
}
