package io.github.bitaron.auditLog.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a method whose invocations should be recorded as audit log entries.
 * <p>
 * Applying this annotation to a method causes the audit-log starter's AOP aspect to intercept
 * both successful returns and thrown exceptions, capture the method's arguments and outcome,
 * and (asynchronously, off the caller's thread) persist one audit record per matching template
 * in {@link #templateNameList()}.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface Audit {

    /**
     * A high-level category for the audited action (e.g. "AUTH", "PAYMENT", "USER_MANAGEMENT").
     * Stored verbatim on the persisted {@code AuditLog} record.
     *
     * @return the audit type; required, has no default
     */
    String auditType();

    /**
     * A short, human-readable name for the specific action being audited (e.g. "login-attempt").
     *
     * @return the action name, or empty string if not set
     */
    String actionName() default "";

    /**
     * The kind of operation being audited (e.g. "CREATE", "UPDATE", "DELETE").
     *
     * @return the action type, or empty string if not set
     */
    String actionType() default "";

    /**
     * When set, records generated by this invocation are associated with a shared audit group,
     * useful for correlating multiple audit entries produced by one logical operation.
     *
     * @return the group name, or empty string to skip grouping
     */
    String groupName() default "";

    /**
     * Names of the {@code audit_template} rows used to render this method's audit message(s).
     * One audit log row is persisted per matching, existing template name. If empty, a single
     * audit log row is still persisted with a default message and no template association.
     *
     * @return the template names to resolve against
     */
    String[] templateNameList() default {};

    /**
     * When {@code true}, the actor is recorded as the system itself (actor id/name
     * {@code "SYSTEM"}) rather than derived from the current request or security context.
     * Intended for scheduled jobs and other non-request-driven invocations.
     *
     * @return whether this invocation should be attributed to the system actor
     */
    boolean isActorSystem() default false;

    /**
     * When {@code true} (the default), actor and client information is resolved the standard
     * way: from the configured {@code AuditLogGenericDataGetter} if present, otherwise from the
     * current HTTP request. When {@code false}, the audited method's return value is expected to
     * implement {@code AuditLogGenericDataGetter} directly, so actor data can be derived from the
     * method's own result instead.
     *
     * @return whether to use the common actor-resolution strategy
     */
    boolean isActorCommon() default true;
}
